version: "3.4"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - WWWUSER=${WWWUSER:-1000}
        - WWWGROUP=${WWWGROUP:-1000}
    image: ghcr.io/devgine/composer-php:v2-php8.3-alpine
    restart: unless-stopped
    container_name: eloquent-validator-php
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
    tty: true
    stdin_open: true