version: "3.4"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: ghcr.io/devgine/composer-php:v2-php8.3-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    container_name: eloquent-validator-php
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '.:/var/www/html'